version: '2'
services:
  zira-graphql:
    restart: always
    container_name: zira-graphql
    image: zira-graphql
    expose:
      - '80'
    networks:
      - zira
networks:
  zira:
    external: true
