eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zira-graphql
  profiles:
    active: local
logging:
  level:
    com.example.ziragraphql.service: debug